name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.9.4 # Define the elixir version [required]
        otp-version: 22.2 # Define the OTP version [required]
    - name: Install Dependencies
      run: mix deps.get
    - name: Copy Rebar config
      run: cp config/rebar.config deps/qErlang
    - name: Run Tests
      run: mix test --no-start
    - name: Build release files
      run: MIX_ENV=prod mix release
    - name: Create dataset directory
      run: mkdir -p _build/prod/rel/basket/deps/SnP500s/data
    - name: Copy constituents file
      run: cp deps/SnP500s/data/constituents.csv _build/prod/rel/basket/deps/SnP500s/data
    - name: Archive distribution
      run: cd _build/prod/rel/ && tar -czvf basket.tgz basket
    - uses: actions/upload-artifact@v1
      with:
        name: basket
        path: _build/prod/rel/basket.tgz
